apiVersion : apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: k8s-apps
spec:
  selector:
    matchLabels:
      project: main
  template:
    metadata:
      labels:
        project: main
    spec:
      containers:
        - name: app-web
          image:  eugentk/go-app:latest
          ports:
            - containerPort: 8888